# Generated by Django 4.0.5 on 2022-06-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_description_ar_food_description_ru_food_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
